model_name: "Qwen/Qwen3-4B"

batch_size: 8
grad_accum_steps: 1
num_episodes: 2000
learning_rate: 1e-5
thinking_max_tokens: 300
output_max_tokens: 600
multi_gpu: "ddp"

wandb_project: "hardmath hints"
wandb_run_name: "qwen3-4b"

# Prompt builder â€“ HARDMath dataset via direct JSON URL
prompt_builder_cls: "src.prompt_builders.hardmath.HardMathPromptBuilder"
prompt_builder_params:
  dataset_url: "https://raw.githubusercontent.com/sarahmart/HARDMath/refs/heads/main/data/HARDMath.json"

rewards:
  - cls: "boxed_answer"
    params:
      coefficient: 1.0
      log_thinking: false

  - cls: "judge_reward"
    params:
      model: "gpt-4o-mini"
      coefficient: -2.0
      log_thinking: true
      judge_prompt_template: "hint_used"


